---
services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./app:/app
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - wmnet

    php:
        image: php:fpm
        volumes:
            - ./app:/app
        networks:
            - wmnet
        command:
            - /bin/sh
            - -c
            - |
                docker-php-ext-install mysqli
                php-fpm

    db:
        image: mysql:latest
        ports:
            - 3306:3306
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wm
            MYSQL_USER: user1
            MYSQL_PASSWORD: user1
        networks:
            - wmnet

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        ports:
            - 5502:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - wmnet

networks:
    wmnet:
